### PR TITLE
Update setup-makefiles.sh

### PR DESCRIPTION
**Pull request by ppinter1**
I had trouble building this branch until I changed this to read "proprietary-blobs.txt".
Same change also needed in extract-files.sh

### CODE REVIEW

**Comment by brainstorm** [comment]
I can confirm both pull-requests from ppinter1.

Additionally, I own a Nexus 4 and have not been able to retrieve the binary blobs below from the device itself nor in the Google drivers page(s):

https://dl.google.com/dl/android/aosp/broadcom-mako-lmy48t-decb9f51.tgz
https://dl.google.com/dl/android/aosp/lge-mako-lmy48t-ff9ca8d1.tgz
https://dl.google.com/dl/android/aosp/qcom-mako-lmy48t-8c489b7e.tgz

```
ninja: error: 'vendor/lge/mako/proprietary/etc/DxHDCP.cfg', needed by '/home/romanvg/android/system/out/target/product/mako/system/etc/DxHDCP.cfg', missing and no known rule to make it
ninja: error: 'vendor/lge/mako/proprietary/vendor/lib/libwvdrm_L1.so', needed by '/home/romanvg/android/system/out/target/product/mako/system/vendor/lib/libwvdrm_L1.so', missing and no known rule to make it

vendor/lge/mako/proprietary/vendor/lib/drm/libdrmwvmplugin.so
vendor/lge/mako/proprietary/vendor/lib/libwvm.so
vendor/lge/mako/proprietary/vendor/lib/libWVphoneAPI.so
vendor/lge/mako/proprietary/vendor/lib/libWVStreamControlAPI_L1.so
vendor/lge/mako/proprietary/vendor/lib/mediadrm/libwvdrmengine.so
```

I have `touch`'d those files to proceed further with the build, but I would like to know if those are really required and/or if at least @ppinter1 has those?

**Comment by brainstorm** [comment]
Are there automated means to retrieve those blobs from public `mako` stock ROMs?

**Comment by ppinter1** [comment]
I'm not sure it's germane, but I had already sideloaded the new LegacyOS 14.1 Nightly onto my Nexus 4 *before* following the new mako wiki to build LOS from source.

In other words, these pull request changes helped me extract the blobs from an adb connected Nexus 4 already running LOS 14.1.

Do we have a chicken-and-egg situation here?

Maybe I'll know more if my LOS build ever finishes (it's been two days and it's still grinding away).

**Comment by ppinter1** [comment]
Closing as redundant as the same change was subsequently made via Gerrit; I guess pull requests aren't used by LineageOS?

**Pull request closed without merging**
